# Generated by Django 5.0.4 on 2024-04-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sss_app', '0002_product_image_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
