# Generated by Django 5.0.4 on 2024-04-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sss_app', '0005_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
