# Generated by Django 5.0.4 on 2024-04-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss_app', '0007_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
